# Generated by Django 4.1.1 on 2022-09-15 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0002_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="comment",
        ),
    ]
